name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: weather_station
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather_station_${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
